# netlify.toml
[build]
  command = "npm run build"
  publish = "dist/camel"

[[redirects]]
  from = "/api/*"
  to = "https://homeo-work-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200