[build]
  command = "ng build --configuration production --output-path=dist --base-href=/"
  publish = "dist"

[context.production.environment]
  NETLIFY_ANGULAR_RUNTIME = "false"

[[redirects]]
  from = "/api/*"
  to = "https://homeo-work-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200