[build]
  command = "ng build --configuration production --no-ssr --output-path=dist/camel/browser --base-href=/"
  publish = "dist/camel/browser"
  
[[redirects]]
  from = "/api/*"
  to = "https://homeo-work-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200