[build]
  command = "npm run build"
  publish = "dist/camel"

[[redirects]]
  from = "/api/*"
  to = "https://homeo-work-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Single Page Application (SPA) útvonalkezelés
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

